# Generated by Django 2.1 on 2018-08-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180809_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='udpated_at',
            new_name='updated_at',
        ),
    ]
